/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type CanSocketProxy = CanSocketNative
export declare class CanSocketNative {
  constructor(interfaceName: string, callback: (frame: { id: number, data: Buffer}) => void)
  write(id: number, data: Buffer): void
  close(): void
  getWriteQueueSize(): number
  setSendBufferSize(size: number): void
}
export declare class CanSocket { }
